<?php
	$pageDetail = $this->getMageportfolio();
?>
<ul>
<?php foreach($pageDetail as $key=>$value) {?>
<li>
<div>
	<div id="portfolio-header">
		<h3><?php echo $value['title'];?></h3>
	</div>
	<div id="portfolio-content">
		<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$value['filename'];?>" height="500" width="500" alt="<?php echo $value['title'];?>"><br/><br/>
		<?php echo $value['content'];?>
	</div>
</div>
</li>
<?php } ?>
</ul>
